### ISSUE TITLE
Backup stopped working with v26.6.0

### ISSUE THREAD

**Issue by IsThisThingStillOn** [jhonderson/actual-http-api#99]
Since Actual Budget v26.6.0 the [backup script](https://github.com/jhonderson/actual-http-api/blob/main/examples/budget_backup.sh) stopped working.

Output of docker terminal for actual -http-api:
```
Unknown error while interacting with Actual Api. See server logs for more information TypeError: archiver is not a function                                            
    at Object.exportData (/usr/src/app/src/v1/budget.js:396:21)                                                                                                        
    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)                                                                                     
    at async /usr/src/app/src/v1/routes/settings.js:221:40
```

Server logs in docker show no more information.

**Comment by x-rous** [comment]
@jhonderson @IsThisThingStillOn I have already implemented a fix for this and there is an open PR for it PR #92
