### ISSUE TITLE
API alignment with @actual-app/api v26.6.0 - improvements and missing endpoints

### ISSUE THREAD

**Issue by x-rous** [jhonderson/actual-http-api#87]
Hi @jhonderson!

I've been using `actual-http-api` a lot and wanted to give back by doing a thorough comparison against the current `@actual-app/api` v26.6.0 surface and the official Actual Budget API reference docs. I found a few areas worth improving (with the help of AI) - some small fixes, some new endpoints, and some DX improvements.

I'm planning to work through these and open individual PRs, so this issue is just to give you visibility and a chance to steer anything before I start. Happy to discuss any item if you'd prefer a different approach!

I'll tick each checkbox as the corresponding PR is merged and close this issue once everything is done. That said, I'd love your thoughts before I dive in - feel free to push back on anything that doesn't align with your vision for the project, or if you'd prefer a different approach on any item. Happy to skip or rethink anything on the list!

> **Note on breaking changes:** most items below are additive or internal-only and won't affect existing integrations. The one exception is marked with ⚠️ and I'll open a discussion before submitting that PR.

### 🔴 Correctness

- [x] **[C1] `deleteTransactions` async handling** - the current implementation uses `forEach` with an `async` callback, which doesn't await the promises. Replacing it with `for...of` ensures all deletes complete before the batch closes.
_Internal fix only - no change to the HTTP interface or response shape._
Addressed in PR #88.

- [x] **[C2] Notes implementation** - the current note functions use internal API paths that aren't part of the public `@actual-app/api` surface. PR [actualbudget/actual#7769](https://github.com/actualbudget/actual/pull/7769) (merged May 2026) added official `getNote(id)` and `updateNote(id, note)` methods that we can use instead, which will be much more resilient to upstream changes.
_Internal fix only - no change to the HTTP interface or response shape._
Addressed in PR #89.

### 🟠 Missing endpoints

- [x] **[M1] `getIDByName`** - upstream exposes `getIDByName(type, name)` for accounts, schedules, categories, and payees. Useful for integrations that store names rather than UUIDs. Route: `GET /v1/budgets/:budgetSyncId/id-by-name?type=accounts&name=Checking`
_Additive - new endpoint, no impact on existing integrations._
Addressed in PR #97.

- [x] **[M2] `getCommonPayees`** - upstream exposes `getCommonPayees()` which returns the built-in transfer payees. Needed to create transfer transactions programmatically. Route: `GET /v1/budgets/:budgetSyncId/payees-common`
_Additive - new endpoint, no impact on existing integrations._
Addressed in PR #98.

- [x] **[M3] `aqlQuery`** - upstream has marked `runQuery` as `@deprecated` in favour of `aqlQuery`. The existing `/run-query` route will be updated internally to call `actualApi.aqlQuery` instead of `actualApi.runQuery`, keeping the HTTP surface identical. Both methods are functionally identical today so this is a zero-risk internal swap.
_Internal fix only - no change to the HTTP interface or response shape._
Addressed in PR #100.

- [x] **[M4] Notes HTTP endpoints aligned to official methods** - once the internals are updated, confirm the entity-specific note routes (`categories`, `accounts`, `months`) are correctly wired to `actualApi.getNote` and `actualApi.updateNote`. Optionally add a generic `GET /notes/:entityId` / `PUT /notes/:entityId` for flexibility.
_Internal fix only - no change to the HTTP interface or response shape._
Pending merge of PR #89.

### 🟡 Incomplete parameters

- [x] **[P1] `createAccount` - `initialBalance` not forwarded** - the upstream signature accepts an optional `initialBalance` second argument but it isn't accepted or forwarded by the HTTP route, so all accounts are created with a zero balance.
_Additive - new optional request body field, no impact on existing integrations._
Addressed in PR #93.

- [x] **[P2] `getCategories` / `getCategoryGroups` - `hidden` option not forwarded** - upstream accepts `{ hidden?: boolean }` but the wrappers call these with no options. Adding a `?hidden=true` query parameter would let callers retrieve hidden categories and groups.
_Additive - new optional query parameter, no impact on existing integrations._
Addressed in PR #94.

- [x] **[P3] `updateSchedule` - `resetNextDate` not forwarded** - the upstream third argument isn't exposed, so callers can't trigger a next-date recalculation via the API.
_Additive - new optional request body field, no impact on existing integrations._
Addressed in PR #95.

- [x] ~**[P4] `runBankSync` - options hardcoded** - the wrapper constructs `{ accountId }` manually rather than forwarding the full options object, which would make it easier to support any future upstream additions.
_Additive - no impact on existing integrations._~
After verifying against the installed @actual-app/api@26.6.0 type definitions, runBankSync only accepts { accountId?: string } — there are no additional options to forward. The existing implementation already handles both cases correctly via two separate routes (/accounts/:accountId/banksync for per-account sync and /accounts/banksync for all accounts). No code fix is needed.

- [x] **[P5] Budget month fields** - PR [actualbudget/actual#7526](https://github.com/actualbudget/actual/pull/7526) added `budgeted`, `received`, `balance`, and `carryover` to the `getBudgetMonth` response. Worth verifying these pass through and documenting them in the Swagger response schemas.
_Additive - new fields in existing response, no impact on existing integrations._
Addressed in PR #96.

### 🔵 Developer experience

- [x] **[D1] JSDoc types aligned with `@actual-app/api/models`** - PR [actualbudget/actual#7581](https://github.com/actualbudget/actual/pull/7581) (v26.5.0) introduced a stable public `@actual-app/api/models` entry point. Adding JSDoc annotations referencing these types would give TypeScript consumers (MCP servers, Home Assistant integrations, etc.) type inference without needing a full `.ts` migration.
_Additive - no impact on existing integrations._
Investigated and skipped - `@actual-app/api/models` uses `export type *` which is erased at runtime, so there is no runtime content to work with. The Swagger/OpenAPI docs already cover the entity shapes for HTTP consumers.

- [x] **[D2] Swagger/OpenAPI docs for newer endpoints** - tags, schedules, bank sync, and the export endpoint have sparse annotations. Filling these in would make the `/api-docs/` experience much better for new users.
_Additive - no impact on existing integrations._
Verified and no changes needed - all routes already have complete Swagger annotations with summary, parameters, requestBody, and responses.

- [x] **[D3] ⚠️ Consistent error response shape** - errors across routes currently return different shapes. A centralized error middleware normalizing everything to `{ "error": { "code": "...", "message": "..." } }` would make integrations much easier to build reliably. [To be considered separately in a new issue]
_**Potentially breaking** - existing integrations that parse error responses may need to be updated. I'll open a discussion before submitting this PR so we can agree on the best approach._

- [x] **[D4] Input validation** - request bodies are forwarded to the API without validation, so missing required fields return opaque upstream errors rather than clear `400` responses. Light validation before calling the API would noticeably improve the debugging experience. [To be considered separately in a new issue]
_Additive - no impact on existing integrations that send valid request bodies._

- [x] **[D5] Test coverage for newer endpoints** - tags, bank sync, export, schedules, and rules don't have test coverage yet. I'll aim to add tests alongside each PR so nothing regresses. [To be considered separately in a new issue]
_No impact on existing integrations._

**Comment by jhonderson** [comment]
Hello, thanks for putting this together. I am happy to review/approve your changes, and after reading your check list I have no concerns. As long as this wrapper keeps doing what is doing right now, which is simply exposing the nodejs library through a http api, I am happy to improve these aspects. I'll close https://github.com/jhonderson/actual-http-api/issues/81 in favour of this. If you disagree feel free to re-open.

**Comment by x-rous** [comment]
## Additional Findings

### 🔴 Correctness

- [x] [C3] **getAccountBalance - string date passed where Date object expected** - The route passes req.query.cutoff_date (a raw query string) directly to actualApi.getAccountBalance, which the type definitions declare as getAccountBalance(id: string, cutoff?: Date). Passing a string where a Date is expected is a type mismatch that could produce incorrect results if the API performs date arithmetic internally. Fix: parse the string in the route before forwarding - new Date(req.query.cutoff_date).
_Internal fix only - no change to the HTTP interface or response shape._
Addressed in PR #90.

- [x] [C4] **updateRule - :ruleId path parameter is completely ignored** - The PATCH /rules/:ruleId route never reads req.params.ruleId. The upstream signature is updateRule(rule: RuleEntity) where the rule object must include its own id, meaning callers are silently required to include id in the request body even though the URL already has it. This is inconsistent with every other update endpoint in the codebase and allows a caller to hit /rules/abc while updating rule xyz if the body contains id: xyz. Fix: inject the path ID into the rule - { ...req.body.rule, id: req.params.ruleId } - the same pattern already used by updateTransaction.
_Internal fix only - no change to the HTTP interface or response shape._
Addressed in PR #91.

### 🔵 Developer experience

- [x] [D6] **Swagger schema - name field typed as integer in two budget month schemas** - Both BudgetMonthCategoryGroup and BudgetMonthCategory schemas in budget-months.js declare name: type: integer when it should be type: string. Documentation-only fix, no logic changes. Bundled with the [P5] PR since both touch the same file.
_Documentation fix only - no impact on existing integrations._
Addressed in PR #96.

**Comment by x-rous** [comment]
## Additional Findings

### 🔴 Correctness

- [x] **[C5] Export endpoint after `archiver` v8 ESM upgrade** - regression introduced by #83, which upgraded `archiver` from `7.0.1` to `8.0.0`. Archiver v8 moved to ESM / Node 18+ and no longer behaves like the old CommonJS callable export used by `archiver('zip', ...)`, causing the export endpoint to fail at runtime with `TypeError: archiver is not a function`. Updating the implementation to use the v8-compatible `ZipArchive` export should restore the export endpoint.
_Internal fix only - no change to the HTTP interface or response shape._
Addressed in PR #92.

**Comment by x-rous** [comment]
@jhonderson I'm done with the changes, appreciate if you can review the PRs and share your feedback, there are no interdependencies between the PRs so you can approve them in any order without having to update to the latest merge.

**Comment by jhonderson** [comment]
Hello Manaf,

Thanks for all your contributions — they’ve all been merged now. I’ll create a small `26.6.1` release specifically to get these fixes into the `:latest` tag.

I’d also appreciate hearing about your workflow for finding these issues and improvement opportunities so quickly, and for breaking them down into small, independent PRs. I know how to approach this manually the traditional way, but if you’re using AI or other tooling to speed things up, I’d be interested in hearing about it. If not, no worries.

Thanks!
Jhon

cc @x-rous

**Comment by x-rous** [comment]
@jhonderson 

I’ve been using Claude to speed up the initial review and discovery work, then I manually filter, validate, and break the findings down into changes that are actually worth submitting.

My flow is roughly:

1. Ask Claude to review the repo code from the perspective of correctness, and compare it with the code the original node @actual-app/api in actual repo 
2. Take the findings and manually check which ones are real issues versus noise.
3. Ask Claude to create a high level fix .md plan and create independent PRs where possible.
4. Take the fix .md plan into VS Code and start working there.

In this case, the PRs were easier to separate because almost all of them touched different files. I tried to keep each PR focused on one clear issue rather than bundling everything together.

Happy to discuss further.
